version: "3.7"
services:
  app1:
    build: ./app1
    container_name: app1
    ports:
      - 5000:5000
    links:
      - "app2"
    depends_on:
      - "app2"
    networks:
      - appnet
  app2:
    build: ./app2
    container_name: app2
    ports:
      - 5001:5001
    networks:
      - appnet
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 14268:14268
      - 6831:6831/udp
      - 14269:14269
      - 14267:14267
      - 14250:14250
      - 9411:9411
      - 4317:4317
    networks:
      - appnet
networks:
  appnet:
    name: "appnet"
    driver: bridge
